apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-usercenter
  newTag: 8254b45576385d533f8ed1baa62384845cb44efa
kind: Kustomization
namespace: openeuler-usercenter
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: chenqi
  kubernetes.ops.region: hk
resources:
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- secret.yaml
