resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- pvc.yaml
- ingress.yaml
commonLabels:
  app: sync-bot
commonAnnotations:
  email: openeuler.syncbot@gmail.com
  owner: chenyanpan
namespace: sync-bot
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/sync-bot
  newTag: 1ff2c3c4c7e7d4324a70a56ca2cf87a7cb51c794
