apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-verification-deployment
  namespace: repo-post-verification
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: post-verification
  template:
    metadata:
      labels:
        app: post-verification
    spec:
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-post-verification:1f9a9889deb88fb14dc5a3e955ec259b5f4fb7f1
        imagePullPolicy: Always
        name: post-verification
        env:
        - name: accessToken
          valueFrom:
            secretKeyRef:
              key: accessToken
              name: post-verification-secrets
        - name: jasypt.encryptor.password
          valueFrom:
            secretKeyRef:
              key: jasypt.encryptor.password
              name: post-verification-secrets
        - name: accessToken
          valueFrom:
            secretKeyRef:
              key: access_token
              name: post-verification-secrets
        - name: rootSalt
          valueFrom:
            secretKeyRef:
              key: rootSalt
              name: post-verification-secrets
        - name: secretKey
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: post-verification-secrets
        resources:
          requests:
            cpu: 2000m
            memory: 4000Mi
          limits:
            cpu: 4000m
            memory: 8000Mi
        volumeMounts:
        - mountPath: /var/log
          name: log-data-volume
        - mountPath: /app-publish/privatekey
          name: ssh-private-key
        - mountPath: /usr/local/primary/ocpFile.ks
          name: ssh-private-key
          subPath: primary-ks
        - mountPath: /usr/local/standby/tcsFile.ks
          name: ssh-private-key
          subPath: standby-ks
        - mountPath: /usr/local/work/tcwFile.ks
          name: ssh-private-key
          subPath: work-ks
      volumes:
      - name: log-data-volume
        persistentVolumeClaim:
          claimName: openeuler-log-data-volume
      - name: ssh-private-key
        secret:
          secretName: post-verification-secrets