resources:
- pvc.yaml
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml
- ingress.yaml
commonAnnotations:
  email: xiongfengbo@huawei.com
  owner: xiongfengbo
namespace: repo-post-verification
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-post-verification
  newTag: 9161e7b01d497be5db576d2a43db26a689107385
