resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- sa.yaml
commonAnnotations:
  email: 245462755@qq.com
  owner: zhengyuhang
namespace: openlookeng-website-frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng_website
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng_website
  newTag: d6b0e3bdb9fed4dd9c5d4bcf96551d45363704fb
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openlookeng_website
  newTag: 074d23f06a8ec4d91cdf661c8f419e8066e2fb47
