resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: openeuler-website-v2
commonAnnotations:
  email: 245462755@qq.com
  owner: zhengyuhang
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-backend
  newTag: main-c903a9
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-frontend
  newTag: 273f8508775daadf38c06920f6121ad551696516
