kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- service.yaml
- secrets.yaml
- configmap.yaml
commonLabels:
  label: mirrorbits
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylikehu
namespace: repo-mirrorbits
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-mirrorbits
  newTag: e7b8f21810a64796492ca62a0f681ee143370d76
