apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/custom-http-errors: "404"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* injectedEnvVars/$ {
       return 403;
      }
      location ~* /script$ {
       return 403;
      }
  name: jenkins-cn-north4-2-ingress
spec:
  tls:
    - hosts:
        - openeulerjenkins.osinfra.cn
      secretName: jenkins-cn-north4-tls
  rules:
    - host:  openeulerjenkins.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: oauth2-proxy
              servicePort: 4180
            path: /
