apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: openeuler
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: yangwei
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/defect-manager-prod
  newTag: 4fb1fd5de8b5421100f277e1ecb0b95e80e394fb
kind: Kustomization
namespace: cve-defect-manager
resources:
- manager-deployment.yaml
- ingress.yaml
- service.yaml
