apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: openeuler
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: yangwei
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/defect-manager-prod
  newTag: 3efa937fd19ffbff29c562702193e26ab1a9b4a5
kind: Kustomization
namespace: cve-defect-manager
resources:
- manager-deployment.yaml
- ingress.yaml
- service.yaml
