resources:
- service.yaml
- deployment.yaml
- sa.yaml
- networkpolicy.yaml
- namespace.yaml
namespace: yocto-meta-openeuler
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/yocto-meta-openeuler
  newTag: v1.0.20240514150523
