apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- secrets.yaml
- service.yaml
- pvc.yaml
- configmap.yaml
- cronjob.yaml
namespace: mail
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/patchwork/patchwork
  newTag: v1.0.20240620142325
