apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - cronjob.yaml
resources:
- deployment.yaml
- secrets.yaml
- service.yaml
- pvc.yaml
- configmap.yaml
namespace: mail
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/patchwork/patchwork
  newTag: main-68e430
