---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patchwork-share-disk-volume
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-disk
  volumeMode: Filesystem

