apiVersion: v1
kind: Service
metadata:
  name: patchwork-service
  namespace: mail
spec:
  ports:
  - name: httpport
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: patchwork
  type: ClusterIP
