resources:
  - pvc.yaml
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - nginx-html-configmap.yaml
commonLabels:
  app: repo-nginx-pod
commonAnnotations:
  owner: caozhi
  email: "caozhi1214@gmail.com"
namespace: repo2
