---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updating-openeuler-sigs
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'openeuler-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          serviceAccountName: openeuler-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_openeuler-c01c5b
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py genegroup
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: upload-meeting-video
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'openeuler-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          serviceAccountName: openeuler-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_openeuler-c01c5b
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              command:
                - /bin/sh
                - -c
                - |
                  strip -R .note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3
                  python manage.py handle_recordings
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: upload-to-bilibili
spec:
  schedule: "10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'openeuler-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          serviceAccountName: openeuler-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_openeuler-c01c5b
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py upload_to_bilibili
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-examination
spec:
  schedule: "20 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'openeuler-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          serviceAccountName: openeuler-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_openeuler-c01c5b
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py check_examination
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-activity-status
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'openeuler-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          serviceAccountName: openeuler-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:dev_openeuler-c01c5b
              env:
              - name: TZ
                value: Asia/Shanghai
              - name: CONFIG_PATH
                value: /vault/secrets/secrets.yaml
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py update_activity_status

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-privacy-policy-cronjob
  namespace: meetingserver
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'openeuler-meeting'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          serviceAccountName: openeuler-meeting
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          restartPolicy: Never
          containers:
          - name: meeting-server
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:1d85f6cef04f39fc3b95686a65e7f26eb29638b8
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            command:
              - /bin/sh
              - -c
              - |
                python manage.py check_privacy_policy_update
