# Deployment for meeting service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: meeting-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-server
      component: web-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'openeuler-meeting'
        vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
          {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
          {{ .Data.data.config }}
          {{- end }}
      labels:
        app: meeting-server
        component: web-server
    spec:
      serviceAccountName: openeuler-meeting
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: meeting-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:78217d14b8b116680f84b0d7ad4a78d0deb037bc
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: CONFIG_PATH
          value: /vault/secrets/secrets.yaml
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        command:
          - /bin/sh
          - -c
          - |
            strip -R .note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3
            touch /work/app-meeting-server/meetings/migrations/__init__.py
            python manage.py collectstatic
            exec uwsgi --ini /work/app-meeting-server/deploy/production/uwsgi.ini

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: schedule-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'openeuler-meeting'
        vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/openeuler/openeuler-meeting'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
          {{- with secret "internal/data/openeuler/openeuler-meeting" -}}  
          {{ .Data.data.config }}
          {{- end }}
      labels:
        app: meeting-server
    spec:
      serviceAccountName: openeuler-meeting
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
        - name: schedule-task
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server:1d85f6cef04f39fc3b95686a65e7f26eb29638b8
          env:
          - name: TZ
            value: Asia/Shanghai
          - name: CONFIG_PATH
            value: /vault/secrets/secrets.yaml
          command:
            - /bin/sh
            - -c
            - |
              python manage.py sendmessages

