resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- tls.yaml
namespace: openeuler-quickissue-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-quickissue
  newTag: 660218f284951efce6948efdc5e61e77872fa635
