resources:
- namespace.yaml
- website-deployment.yaml
- backend-deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- sa.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-reproducible
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-reproducible-backend
  newTag: v1.0.20240716112922
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-reproducible-website
  newTag: ed11ff79c32c78552cf53fd7517cce2b82174a50
