resources:
- namespace.yaml
- website-deployment.yaml
- backend-deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml
commonAnnotations:
  email: 747802914@qq.com
  owner: liuyang
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-reproducible
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-reproducible-backend
  newTag: v1.0.20230310170018
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-reproducible-website
  newTag: bb3c52abd4e5d659c2a13b770c0083d7e7e76de2
