---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: website-deployment
  namespace: openeuler-reproducible
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
        vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
        vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/openeuler/website-tls"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with secret "internal/data/openeuler/website-tls" -}}
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/openeuler/website-tls"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "internal/data/openeuler/website-tls" -}}
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/openeuler/website-tls"
        vault.hashicorp.com/agent-inject-template-abc.txt: |
          {{- with secret "internal/data/openeuler/website-tls" -}}
          {{ .Data.data.certificatePassword }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/openeuler/website-tls"
        vault.hashicorp.com/agent-inject-template-dhparam.pem: |
          {{- with secret "internal/data/openeuler/website-tls" -}}
          {{ .Data.data.dhparamPem }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: openeuler-reproducible
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
      labels:
        app: website
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccount: openeuler-reproducible
      automountServiceAccountToken: false
      containers:
      - name: website
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-reproducible-website:6c132447dde58b20611d14c19b721dcf35171b88
        env:
        - name: DET_URL
          value: https://reproducible-builds.openeuler.org
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
            httpHeaders:
            - name: "Host"
              value: "reproducible-builds.openeuler.org"
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
            httpHeaders:
            - name: "Host"
              value: "reproducible-builds.openeuler.org"
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      volumes:
        - name: token-vol
          projected:
            sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
