resources:
- ingress.yaml
- namespace.yaml
- service.yaml
- oauth-proxy.yaml
- secrets.yaml
- cronjob.yaml
commonLabels:
  app: openlookeng-jenkins
commonAnnotations:
  email: caozhi1214@gmail.com
  owner: caozhi
patchesJson6902:
- path: selector.yaml
  target:
    kind: Service
    name: openlookeng-jenkins-internal
    version: v1
namespace: openlookeng-jenkins
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: fc7cbd36549e0ff0f6f019916a1972ec09c52044
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
