resources:
- cronjob.yaml
- openeuler-ci.yaml
- namespace.yaml
- ingress.yaml
- oauth-proxy.yaml
- service.yaml
namespace: jenkins-internal-service
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: main-9ac626-gitee
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-ci
  newTag: 702c396661bcb961bfda7558b25c735d6f705f0c
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
