apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  email: 245462755@qq.com
  owner: zhengyuhang
commonLabels:
  name: website-docs
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-docs
  newTag: v1.0.20240722081835
kind: Kustomization
namespace: website-docs
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- tls.yaml
