apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: openeuler-cn4-jenkins-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: yuchunao
  kubernetes.ops.region: beijing
kind: Kustomization
namespace: openeuler-signatrust
resources:
- website-service.yaml
- website-deployment.yaml
- configmap.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/signatrust/signatrust-app
  newTag: 428bafebce3ba2b67320733e7b0c768169e6fd60
