resources:
- deployment.yaml
- service.yaml
- secret.yaml
- ingress.yaml
- pvc.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: taofeihu
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-easyeditor
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/easyeditor/server
  newTag: v1.0.20240617161420
