apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easyeditor-data
  namespace: openeuler-easyeditor
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-disk
  volumeMode: Filesystem

