resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: cve-manager
  owner: zhangjianjun
commonAnnotations:
  email: 841670711@qq.com
  owner: zhangjianjun
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/cve-manager
  newTag: 84ecd2a71fc78005e4ef928e7cf7f2851297e34b
