apiVersion: apps/v1
kind: Deployment
metadata:
  name: easysoftware-website-deployment
  namespace: easysoftware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/role: easysoftware
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
        vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
        vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
        vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with secret "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl" -}}
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl" -}}
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl"
        vault.hashicorp.com/agent-inject-template-abc.txt: |
          {{- with secret "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl" -}}
          {{ .Data.data.certificatePassword }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl"
        vault.hashicorp.com/agent-inject-template-dhparam.pem: |
          {{- with secret "internal/data/openeuler/openeuler-openaotm-cn-tls-ssl" -}}
          {{ .Data.data.dhparamPem }}
          {{- end }}
      labels:
        app: website
    spec:
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: infra-seccomp.json
      automountServiceAccountToken: false
      serviceAccountName: easysoftware
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/easysoftware/easysoftware-website-prod:stable-8a33a5
        imagePullPolicy: IfNotPresent
        name: website
        env:
        - name: DET_URL
          value: https://easysoftware.openeuler.openatom.cn
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
            httpHeaders:
            - name: "Host"
              value: "easysoftware.openeuler.openatom.cn"
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
            httpHeaders:
            - name: "Host"
              value: "easysoftware.openeuler.openatom.cn"
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      volumes:
        - name: token-vol
          projected:
            sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
