apiVersion: v1
kind: Service
metadata:
  name: easysoftware-service
  namespace: easysoftware
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: easysoftware
  type: ClusterIP
