apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: om-webserver-secrets
  namespace: om-webserver-oneid
spec:
  name: om-webserver-secrets
  keysMap:
    application_properties:
      path: secrets/data/infra-common/om
      key: application_oneid_properties_new
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: tls-secrets
spec:
  name: tls-secrets
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key
