resources:
- namespace.yaml
- cronjob.yaml
- secret.yaml
namespace: openeuler-hk-cronjob
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/pr-statistics-report
  newTag: v1.0.20240428092656
